'project:
'file: rd-create-object.plantuml
'version: 1.0
'autor:
'date:
'dependencies: no

@startuml
!$Obj = "Message"
!$Method = "create"

'actors'
!$Act = "Operator"

'entities'
!$TableObj = "Table '" + $Obj + "'"
!$TableR = "Table 'roles'"

'boundaries'
!$InterfaceMain = "Interface 'Dashboard'"
!$InterfaceObjMethod = "Interface '" + $Method + " " + $Obj + "'"
'error handling'
!$ErrorMethodLimit = "Error '" + $Method + " " + $Obj + "'"

'controls'
!$displayInterfaceMain = "display " + $InterfaceMain
!$displayInterfaceObjMethod = "display " + $InterfaceObjMethod
!$methodObj = $Method + " " + $Obj
'error handling'
!$checkMethod = "check limit '" + $Method + " " + $Obj + "'"
!$displayError = "display " + $ErrorMethodLimit

actor "$Act" as act

entity "$TableObj" as table_obj
'entity "$TableR" as table_roles

boundary "$InterfaceMain" as interface_main
boundary "$InterfaceObjMethod" as interface_obj_method
'error handling'
boundary "$ErrorMethodLimit" as error_method #red

control "$displayInterfaceMain" as display_interface_main
control "$displayInterfaceObjMethod" as display_interface_obj_method
control "$methodObj" as method_obj
'error handling'
control "$checkMethod" as check_method
control "$displayError" as display_error #red

act -- interface_main
act -- interface_obj_method

interface_main --> display_interface_obj_method : "$methodObj action"
'display_interface_obj_method --> table_roles : "select Dashboard Roles list"
display_interface_obj_method --> interface_obj_method
interface_obj_method --> check_method : "save $Obj action"
check_method --> method_obj : "successful"
method_obj --> table_obj : "insert $Obj"
method_obj --> display_interface_main : "successful"
display_interface_main --> interface_main
'error handling'
check_method --> display_error : "max limit"
display_error --> error_method

note as scenario

  # Normal Flow
  1.0 create Message
  1. Оператор указывает, что хочет добавить виджет сообщения на дэшборд
  2. Система проверяет превышение лимита хранящихся одновременно сообщений
  3. Система отображает виджет на дэшборде
  4. Оператор редактирует виджет
    1. Оператор указывает текст сообщения
    2. Оператор указывает список ответов на сообщение
  5. Система устанавливает флаг сообщения "Не отправлено"
  6. Система выполняет запрос к Базе Данных на создание записи о виджете сообщения

end note
@enduml
