'project:
'file: rd-create-object.plantuml
'version: 1.0
'autor:
'date:
'dependencies: no

@startuml
!$Obj = "BLE Devices List"
!$Method = "get"

'actors'
!$Act = "User"
!$Contr = "Controller"

'entities'
!$DBGATT = "Database 'GATT Specification'"
!$DBDevices = "Database 'Known BLE Devices'"

'boundaries'
!$InterfaceMain = "Interface 'Main Menu'"
!$InterfaceObjMethod = "Interface '" + $Obj + "'"
'error handling'

'controls'
!$displayInterfaceObjMethod = "display " + $InterfaceObjMethod
!$methodObj = $Method + " " + $Obj
!$waitTimeout = "wait for Response '" + $Method + " " + $Obj + "'"
!$recognizeData = "recognize Advertising Data"
'error handling'
!$displayErrorNoRoute = "display Error 'No route to Controller'"
!$displayErrorNoBLE = "display Error 'Bluetooth unsupported'"

actor "$Act" as act
actor "$Contr" as contr

entity "$DBGATT" as db_gatt
entity "$DBDevices" as db_dev

boundary "$InterfaceMain" as interface_main
boundary "$InterfaceObjMethod" as interface_obj_method
'error handling'

''control "$displayInterfaceMain" as display_interface_main
control "$displayInterfaceObjMethod" as display_interface_obj_method
control "$methodObj" as method_obj
control "$waitTimeout" as wait_timeout
control "$recognizeData" as recognize_ad
'error handling'
control "$displayErrorNoRoute" as display_error_no_route #red
control "$displayErrorNoBLE" as display_error_no_ble #red

act -- interface_main
act -- interface_obj_method

interface_main --> method_obj : "$methodObj action"
method_obj -- contr : "send command"
method_obj --> wait_timeout
contr -- wait_timeout : "get response"
wait_timeout --> recognize_ad : "ok"
recognize_ad <-- db_gatt : "ad types, char & attr types"
recognize_ad <-- db_dev : "specs for ad type '0xff'"
recognize_ad --> display_interface_obj_method : "recognized data"
display_interface_obj_method --> interface_obj_method
'error handling'
wait_timeout --> display_error_no_route : "connection error"
wait_timeout --> display_error_no_ble : "bluetooth error"

note as scenario

# Normal Flow

dev_l "get BLE Devices List"
1. Пользователь указывает, что хочет просмотреть Bluetooth сеть
2.ad_r read Advertising Data
  1. Система отправляет запрос Контроллеру на чтение данных оповещения сети
  2. Система получает данные оповещения по всем устройствам сети
3.ad_re recognize Advertising Data
  1. Система отправляет запрос в DB для получения спецификации GATT
  2. Система отправляет запрос в DB для получения спецификации известных устройств
  3. Система формирует список устройств, данные оповещения которых она смогла распознать
4. Система отображает список устройств с распознанными данными

# Exceptions

dev_l.E1 Контроллер недоступен
1. Система отображает сообщение о том, что контроллер недоступен

dev_l.E2 Контроллер не имеет Bluetooth модуля
1. Система отображает сообщение о том, что доступ к функции сканирования сети Bluetooth заблокирован

end note

@enduml
