'project:
'file: use-case.plantuml
'version:
'autor:
'date:
'dependencies: no

@startuml

left to right direction
skinparam packageStyle rectangle
allow_mixing

'actors'

!$Primary = "Actor1"
!$Secondary = "Actor2"

'use case'

!$obj_create = "create Object"
!$obj_read = "read Object"
!$obj_update = "update Object"
!$obj_delete = "delete Object"
!$obj_tag = "tag Object"

actor "$Primary"
actor "$Secondary"

rectangle System {

  rectangle "Object Management" {
    usecase "$obj_create" as obj_cr
    usecase "$obj_read" as obj_rd
    usecase "$obj_update" as obj_up
    usecase "$obj_delete" as obj_dl
    usecase "$obj_tag" as obj_tg
    "$Primary" --> obj_cr
      obj_cr <.. obj_rd : extends
        "$Secondary" -> obj_up
      obj_cr <.. obj_up : extends
        obj_up -> "$Secondary"
      obj_dl .> obj_cr : extends
      obj_tg .up.> obj_cr : include
  }

}

@enduml
